import React, { Fragment, useState } from "react";
import Head from "next/head";
import { Formik, Form } from "formik";

import { signIn } from "next-auth/client";
import { useRouter } from "next/router";
import NextLink from "next/link";

import Avatar from "@material-ui/core/Avatar";
import Button from "@material-ui/core/Button";
import CssBaseline from "@material-ui/core/CssBaseline";
import TextField from "@material-ui/core/TextField";
import FormControlLabel from "@material-ui/core/FormControlLabel";
import Checkbox from "@material-ui/core/Checkbox";
import MuiLink from "@material-ui/core/Link";
import Paper from "@material-ui/core/Paper";
import Box from "@material-ui/core/Box";
import Grid from "@material-ui/core/Grid";
import LockOutlinedIcon from "@material-ui/icons/LockOutlined";
import Typography from "@material-ui/core/Typography";
import { makeStyles } from "@material-ui/core/styles";

import UserLogin from "../../components/login/user/UserLogin";
import AdminLogin from "../../components/login/admin/AdminLogin";

import Copyright from "../../components/copyright/Copyright";

const useStyles = makeStyles((theme) => ({
  root: {
    height: "100vh",
  },
  image: {
    backgroundImage:
      "url(https://images.unsplash.com/photo-1630980260348-16f484cb6471?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80)",
    backgroundRepeat: "no-repeat",
    backgroundColor:
      theme.palette.type === "light" ? theme.palette.grey[50] : theme.palette.grey[900],
    backgroundSize: "cover",
    backgroundPosition: "center",
  },
  paper: {
    margin: theme.spacing(8, 4),
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  avatar: {
    margin: theme.spacing(1),
    backgroundColor: theme.palette.secondary.main,
  },
  form: {
    width: "100%", // Fix IE 11 issue.
    marginTop: theme.spacing(1),
  },
  submit: {
    margin: theme.spacing(3, 0, 2),
  },
}));

function Login() {
  const router = useRouter();
  const [isAdminLogin, setIsAdminLogin] = useState(false);
  const handleSubmit = (values, { setSubmitting }) => {
    setSubmitting(true);
    const signInHandler = async () => {
      const result = await signIn("credentials", {
        redirect: false,
        employeeID: values.employeeID,
        password: values.password,
      });

      if (!result.error) {
        // set some auth state
        router.replace("/profile");
      } else {
        console.log(result.error);
      }
      setSubmitting(false);
    };
    signInHandler();
  };

  const classes = useStyles();

  return (
    <Fragment>
      <Head>
        <title>IEM | FACULTY BOOK | LOGIN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid container component="main" className={classes.root}>
        <CssBaseline />
        <Grid item xs={false} sm={4} md={7} className={classes.image} />
        <Grid item xs={12} sm={8} md={5} component={Paper} elevation={6} square>
          {!isAdminLogin ? (
            <UserLogin setIsAdminLogin={setIsAdminLogin} />
          ) : (
            <AdminLogin setIsAdminLogin={setIsAdminLogin} />
          )}
          <Box mt={2}>
            <Copyright />
          </Box>
        </Grid>
      </Grid>
    </Fragment>
  );
}

export default Login;
