const PublicationSchema = [
  {
    label: "Author's Name",
    value: "",
    info: "Name of the Author of the paper",
    type: "string",
    input_type: "text",
    required: true,
    db_field: "name_of_auth",
  },
  {
    label: "Published on",
    value: "",
    info: "Year of Publication of the paper",
    type: "string",
    input_type: "date",
    required: true,
    db_field: "yop",
  },
  {
    label: "Title",
    value: "",
    info: "Title of the Paper",
    type: "string",
    input_type: "text",
    required: true,
    db_field: "title",
  },
  {
    label: "Journal",
    value: "",
    info: "Name of the Journal",
    type: "string",
    input_type: "text",
    required: true,
    db_field: "journal_name",
  },
  {
    label: "Coverage",
    value: "",
    info: "National/ International",
    type: "string",
    input_type: "select",
    options: ["National", "International"],
    required: true,
    db_field: "nat_inter_imp",
  },
  {
    label: "Impact" /*make this field a color value*/,
    value: "",
    info: "Impact Factor",
    type: "number",
    input_type: "text",
    required: true,
    db_field: "impact_factor",
  },
  {
    label: "Volume No/Issue No. & Page No",
    value: "",
    info: "Volume No/Issue No. & Page No of the paper",
    type: "text",
    input_type: "text",
    required: true,
    db_field: "vol_issue_no",
  },
  {
    label: "ISSN/ISBN",
    value: "",
    info: "ISSN/ISBN of the paper",
    type: "text",
    input_type: "text",
    required: true,
    db_field: "issn_isbn",
  },
  {
    label: "Indexing",
    value: "",
    info: "Indexing of the paper",
    type: "text",
    input_type: "text",
    required: true,
    db_field: "indexing",
  },
  {
    label: "Invited Paper",
    value: null,
    info: "Whether the paper was an invited paper ? Input Yes/No",
    type: "boolean",
    input_type: "checkbox",
    required: true,
    db_field: "inv_paper",
  },
  /*   {
    label: "Proof of Invitation",
    value: null,
    info: "Proof of Invitation (Upload pdf)",
    type: "file",
    input_type: "file",
    required: true,
    db_field: "prof_inv_file",
  }, */
  {
    label: "Students Involved",
    value: "",
    info: "Number of students involved (if any)",
    type: "number",
    input_type: "text",
    required: true,
    db_field: "studs_involved",
  },
  /*   {
    label: "Attachments",
    value: [],
    info: "Attachments",
    type: "file",
    input_type: "file",
    required: true,
    db_field: "attachments",
  }, */
];

export { PublicationSchema };
